#!/usr/bin/env php
<?php

require_once 'vendor/autoload.php';

error_reporting(E_ALL);

use Grigoros\Application;
use Grigoros\Enviroment;

$app = new Application(Enviroment::DEV, __DIR__);

$app->boot();

$app['console']->run();

