#!/usr/bin/env php
<?php
require_once 'vendor/autoload.php';
error_reporting(E_ALL);
use Grigoros\Application;
use Grigoros\Enviroment;

$app = new Application(Enviroment::DEV, __DIR__);

$app->boot();

$app->extend('console', function($console, $app) {
    $em = $app['orm.em'];

    $helperSet = new \Symfony\Component\Console\Helper\HelperSet(array(
        'db' => new \Doctrine\DBAL\Tools\Console\Helper\ConnectionHelper($em->getConnection()),
        'em' => new \Doctrine\ORM\Tools\Console\Helper\EntityManagerHelper($em)
    ));

    $console->setHelperSet($helperSet);
    
    return $console;
});

$app['console']->run();
