silex_home:
    path: /
    defaults: { _controller: 'Controller\IndexController::indexAction' }
    
silex_admin:
    path: /admin
    defaults: { _controller: 'Controller\SecurityController::adminAction' }