silex_home:
    path: /
    defaults: { _controller: 'Grigoros\Controller\IndexController::indexAction' }
    
silex_admin:
    path: /admin
    defaults: { _controller: 'Grigoros\Controller\SecurityController::adminAction' }
    
rss_test:
    path: /rss
    defaults: { _controller: 'Grigoros\Controller\IndexController::rssAction' }
    
silex_test:
    path: /test
    defaults: { _controller: 'Grigoros\Controller\IndexController::testAction' }