silex_home:
    path: /
    defaults: { _controller: 'Grigoros\Controller\IndexController::indexAction' }
    
silex_admin:
    path: /admin
    defaults: { _controller: 'Grigoros\Controller\SecurityController::adminAction' }
    
rss_test:
    path: /rss
    defaults: { _controller: 'Grigoros\Controller\IndexController::rssAction' }

api_test:
    path: /api/test
    defaults: { _controller: 'Grigoros\Controller\ApiController::testAction' }

api_json:
    path: /api/json
    defaults: { _controller: 'Grigoros\Controller\ApiController::jsonAction' }
    
log_request:
    path: /log
    defaults: { _controller: 'Grigoros\Controller\IndexController::logAction' }
