Grigoros\Entity\User:
    type: entity
    table: user
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    
    fields:
        password:
            type: string
            length: 255
        username:
            type: string
            length: 255
        usernameCanonical:
            type: string
            length: 255
            column: username_canonical
        email:
            type: string
            length: 255
        active:
            type: boolean
        locked: 
            type: boolean
        createdAt:
            type: date
            column: created_at
        lastLoginAt:
            type: date
            column: last_login
            nullable: true
        roles:
            type: array
            nullable: true
        
    
    manyToMany:
        groups:
            targetEntity: UserGroup
            inversedBy: users
            cascade: ["persist"]
            joinTable:
                name: user_x_group
                joinColumns:
                    user_id:
                        referencedColumnName: id
            inverseJoinColumns:
                group_id:
                    referencedColumnName: id
    lifecycleCallbacks: {  }
